targets:
  $default:
    builders:
      dart_code_gen:
        enabled: true

builders:
  dart_code_gen:
    import: "package:dart_code_gen/builder.dart"
    builder_factories: ["genSample"]
    build_extensions: {".dart": [".gensample.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
